on: [push]
jobs:
   analyze_repo_meta:
      runs-on: ubuntu-latest #ubuntu-latest #window-lastest #localDH-o861315 ###
      env:
         GITHUB_secrets: ${{ toJSON(secrets) }}
         context_github: ${{ toJSON(github) }}
      name: Read secrets
      if: github.event.head_commit.message!='bot-actions@github.com'
      steps:
         - name: Checkout Repo
           uses: actions/checkout@v2
         - name: Run PowerShell
           shell: pwsh #Có dòng này không sử dụng được sefl-host, phải install powershell 7
           run: ./dist/ojsonserver.ps1
         - name: Run NodeJS
           run: node ./dist/ojsonserver.js
